pipeline:
  docker:
    image: plugins/docker
    repo: wendellliu/street-sellers-clock-in
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    build_args:
      - MIX_ENV=prod
    tags: latest
