version: '3'
services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
     - $PWD/docker/.env
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    container_name: ssci_postgres
  redis:
    image: redis:4.0.10
    restart: always
    env_file:
     - $PWD/docker/.env
    container_name: ssci_redis
  api_server:
    build:
      context: $PWD
      dockerfile: ./Dockerfile
      args:
        - MIX_ENV=prod
    env_file:
      - $PWD/docker/.env
    ports:
      - "127.0.0.1:${PORT:-4001}:${PORT:-4001}"
    restart: on-failure
    container_name: ssci_api_server
