version: '3'
services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
     - $PWD/.env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    container_name: ssci_postgres_prod
  api_server:
    build:
      context: $PWD
      dockerfile: ./Dockerfile
      args:
        - MIX_ENV=prod
    env_file:
      - $PWD/.env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    restart: on-failure
    container_name: ssci_api_server_prod
    links:
      - "postgres:${POSTGRES_HOSTNAME}"
