version: '3'
services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
     - $PWD/deploy/.env
    ports:
      - "${POSTGRES_HOSTNAME}:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    container_name: ssci_postgres_prod
  api_server:
    image: wendellliu/street-sellers-clock-in
    env_file:
      - $PWD/deploy/.env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    restart: on-failure
    container_name: ssci_api_server_prod
